version: "3.6"

services:

  # Нужен для общения с сервисами через AMQP, WS протоколы.
  rabbitmq:
    container_name: ${PROJECT_NAME}-rabbitmq
    image: ${RABBITMQ_TAG:-bitnami/rabbitmq:latest}
    environment:
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME:-admin}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD:-password}
      RABBITMQ_PLUGINS: rabbitmq_management,rabbitmq_consistent_hash_exchange
    ports:
      - ${RABBITMQ_PORT:-5672}:5672
      - ${RABBITMQ_MANAGER_PORT:-15672}:15672

  # Нужен для работы сервисов, которые взаимодействуют с базой данных
  # На данном шаге нужен только для auth-service
  database:
    container_name: ${PROJECT_NAME}-database
    image: egalbox/postgres:2.0.0
    restart: always
    ports:
      - ${DATABASE_PORT:-5434}:5432
    volumes:
      - ./database/data:/var/lib/postgresql/data
    environment:
      POSTGRES_MULTIPLE_DATABASES: interface,monolit,auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-password}

  # Нужен для общения с сервисами через HTTP протокол.
  web-service:
    container_name: ${PROJECT_NAME}-web-service
    image: egalbox/web-service:2.2.1
    ports:
      - ${WEB_SERVICE_PORT:-81}:8080
    environment:
      PROJECT_NAME: ${PROJECT_NAME}
      APP_SERVICE_NAME: web
      RABBITMQ_HOST: ${PROJECT_NAME}-rabbitmq
      RABBITMQ_USER: ${RABBITMQ_USERNAME:-admin}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD:-password}
      WAIT_HOSTS: ${PROJECT_NAME}-rabbitmq:5672
    depends_on:
      - rabbitmq

  auth-service:
    container_name: ${PROJECT_NAME}-auth-service
    image: egalbox/auth-service:2.2.0
    environment:
      APP_SERVICE_NAME: auth
      APP_SERVICE_KEY: uZsLnAJz35FWUTVx@eg#Xirv6I*jcw2Y
      APP_SERVICES: monolit:B#J5mUWKh8FqzQ6Tj0XtYruIcSwpb@ed
      DB_HOST: ${PROJECT_NAME}-database
      DB_PASSWORD: ${DATABASE_PASSWORD:-password}
      RABBITMQ_HOST: ${PROJECT_NAME}-rabbitmq
      RABBITMQ_USER: ${RABBITMQ_USERNAME:-admin}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD:-password}
      WAIT_HOSTS: ${PROJECT_NAME}-rabbitmq:5672, ${PROJECT_NAME}-database:5432
    depends_on:
      - rabbitmq
      - database

  monolit-service:
    container_name: ${PROJECT_NAME}-monolit-service
    build: monolit-service
    volumes:
      - ./monolit-service/:/app/
    environment:
      APP_SERVICE_NAME: monolit
      APP_SERVICE_KEY: B#J5mUWKh8FqzQ6Tj0XtYruIcSwpb@ed
      DB_HOST: ${PROJECT_NAME}-database
      DB_PASSWORD: ${DATABASE_PASSWORD:-password}
      RABBITMQ_HOST: ${PROJECT_NAME}-rabbitmq
      RABBITMQ_USER: ${RABBITMQ_USERNAME:-admin}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD:-password}
      WAIT_HOSTS: ${PROJECT_NAME}-rabbitmq:5672, ${PROJECT_NAME}-database:5432
    depends_on:
      - rabbitmq
      - database